# Generated by Django 6.0.4 on 2026-04-25 12:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('timeout', models.PositiveIntegerField(help_text='Timeout in seconds')),
                ('alert_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('active', 'Active'), ('down', 'Down'), ('paused', 'Paused')], default='active', max_length=10)),
                ('last_heartbeat', models.DateTimeField(default=django.utils.timezone.now)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('webhook_url', models.URLField(blank=True, help_text="Developer's Choice: URL to notify when device goes down", null=True)),
            ],
        ),
    ]
