# Generated by Django 6.0.4 on 2026-04-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_remove_monitor_webhook_url_monitor_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitor',
            old_name='celery_task_id',
            new_name='task_id',
        ),
        migrations.AlterField(
            model_name='monitor',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('down', 'Down')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='timeout',
            field=models.PositiveIntegerField(),
        ),
    ]
