# Generated by Django 6.0.2 on 2026-04-27 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_heartbeat_logs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Heartbeat_logs',
        ),
    ]
