# Generated by Django 6.0.2 on 2026-04-27 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_delete_heartbeat_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeartbeatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status_before', models.CharField(max_length=20)),
                ('note', models.CharField(default='Heartbeat Received!', max_length=255)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeat_logs', to='monitor.monitor')),
            ],
        ),
    ]
